
/**
 * This file is automatically generated through python.
 *
 * If you feel the urge to change anything in it, I recommend
 * to resist and changing the python script which generates it instead.
 *
 * python file: "modbus_gen.py"
 */

#include "stdint.h"
#include "autogenerated_modbus.h"

const Database_declaration_t database_declaration = {
    .mode             = {.address =  100, .minimum =     0, .maximum =     2, .defaultvalue =     1}, // off=0 | pos_control=1 | pwm_control=2 | speed_control=3
    .error            = {.address =  101, .minimum =     0, .maximum =   255, .defaultvalue =     0}, // tracking error
    .commutation      = {.address =  102, .minimum =     0, .maximum =   255, .defaultvalue =     0}, // current commutation value
    .pwm              = {.address =  103, .minimum = -1550, .maximum =  1550, .defaultvalue =     0}, // current pwm value
    .position         = {.address =  104, .minimum =     0, .maximum = 65535, .defaultvalue =     0}, // current position
    .speed            = {.address =  105, .minimum =     0, .maximum = 65535, .defaultvalue =     0}, // current speed on internal slope tracking
    .target           = {.address =  106, .minimum =     0, .maximum = 65535, .defaultvalue =     0}, // positional target
    .speedmax         = {.address =  107, .minimum =     0, .maximum = 65535, .defaultvalue =   180}, // max speed setting (0.001x)
    .acceleration     = {.address =  108, .minimum =     0, .maximum = 65535, .defaultvalue =   100}, // max acceleration setting (0.000001x)
    .control_p        = {.address =  109, .minimum =     0, .maximum =   300, .defaultvalue =    12}, // control loop P
    .control_i        = {.address =  110, .minimum =     0, .maximum =   300, .defaultvalue =    60}, // control loop I
    .i_windup         = {.address =  111, .minimum =     0, .maximum =  1000, .defaultvalue =     5}, // control loop windup (1000x)
    .maxpwm           = {.address =  112, .minimum =     1, .maximum =  1550, .defaultvalue =  1550}, // maximum pwm which is allowed (use for force limit)
};

Database_value_t database_value = {
    .mode             =     1, // [100] off=0 | pos_control=1 | pwm_control=2 | speed_control=3
    .error            =     0, // [101] tracking error
    .commutation      =     0, // [102] current commutation value
    .pwm              =     0, // [103] current pwm value
    .position         =     0, // [104] current position
    .speed            =     0, // [105] current speed on internal slope tracking
    .target           =     0, // [106] positional target
    .speedmax         =   180, // [107] max speed setting (0.001x)
    .acceleration     =   100, // [108] max acceleration setting (0.000001x)
    .control_p        =    12, // [109] control loop P
    .control_i        =    60, // [110] control loop I
    .i_windup         =     5, // [111] control loop windup (1000x)
    .maxpwm           =  1550, // [112] maximum pwm which is allowed (use for force limit)
};
