
/**
 * This file is automatically generated through python.
 *
 * If you feel the urge to change anything in it, I recommend
 * to resist and changing the python script which generates it instead.
 *
 * python file: "modbus_gen.py"
 */

#ifndef AUTOGENERATED_MODBUS_H_
#define AUTOGENERATED_MODBUS_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "stdint.h"

enum {
    DATABASE_LENGTH = 13
};

typedef struct {
    uint16_t address;
    uint16_t minimum;
    uint16_t maximum;
    uint16_t defaultvalue;
} Database_limit_t;

typedef struct {
    Database_limit_t mode; // off=0 | pos_control=1 | pwm_control=2 | speed_control=3
    Database_limit_t error; // tracking error
    Database_limit_t commutation; // current commutation value
    Database_limit_t pwm; // current pwm value
    Database_limit_t position; // current position
    Database_limit_t speed; // current speed on internal slope tracking
    Database_limit_t target; // positional target
    Database_limit_t speedmax; // max speed setting (0.001x)
    Database_limit_t acceleration; // max acceleration setting (0.000001x)
    Database_limit_t control_p; // control loop P
    Database_limit_t control_i; // control loop I
    Database_limit_t i_windup; // control loop windup (1000x)
    Database_limit_t maxpwm; // maximum pwm which is allowed (use for force limit)
} Database_declaration_t;

typedef struct {
    uint16_t mode; // off=0 | pos_control=1 | pwm_control=2 | speed_control=3
    uint16_t error; // tracking error
    uint16_t commutation; // current commutation value
    uint16_t pwm; // current pwm value
    uint16_t position; // current position
    uint16_t speed; // current speed on internal slope tracking
    uint16_t target; // positional target
    uint16_t speedmax; // max speed setting (0.001x)
    uint16_t acceleration; // max acceleration setting (0.000001x)
    uint16_t control_p; // control loop P
    uint16_t control_i; // control loop I
    uint16_t i_windup; // control loop windup (1000x)
    uint16_t maxpwm; // maximum pwm which is allowed (use for force limit)
} Database_value_t;

#ifdef __cplusplus
}
#endif

#endif /* AUTOGENERATED_MODBUS_H_ */
